# Generated by Django 3.2.25 on 2025-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Light', 'Light'), ('Fan', 'Fan'), ('Sensor', 'Sensor'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
